version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.http-client:google-http-client
    versions:
    - 1.38.1
    - 1.39.0
    - 1.39.1
  - dependency-name: com.github.eirslett:frontend-maven-plugin
    versions:
    - 1.11.0
    - 1.11.2
  - dependency-name: com.google.oauth-client:google-oauth-client
    versions:
    - 1.31.4
  - dependency-name: org.scala-lang:scala-library
    versions:
    - 2.13.4
